
//// FILE GENERATED BY TNP /////
import { Morphi } from 'morphi';

import { Controllers as BaselineControllers }  from 'baseline/ss-common-logic/src/controllers';
import * as controllersBaseline from 'baseline/ss-common-logic/src/controllers';
export * from 'baseline/ss-common-logic/src/controllers';



import { ProjectController } from './apps/project/ProjectController';
export { ProjectController } from './apps/project/ProjectController';

export const Controllers: Morphi.Base.Controller<any>[] = [
ProjectController
].concat(BaselineControllers as any) as any;

//#region @backend

import { Helpers } from 'morphi';
import * as _ from 'lodash'

export function controllers<ADDITIONAL={}>(decoratorsControllers?: ADDITIONAL) {
return _.merge(controllersBaseline.controllers(), {

ProjectController: Helpers.getSingleton<ProjectController>(ProjectController),
}  );
}
//#endregion
