
//// FILE GENERATED BY TNP /////
import { Morphi } from 'morphi';

import { Controllers as BaselineControllers }  from 'baseline/ss-common-logic/src/controllers';
import * as controllersBaseline from 'baseline/ss-common-logic/src/controllers';
export * from 'baseline/ss-common-logic/src/controllers';



import { BuildController } from './controllers/BuildController';
export { BuildController } from './controllers/BuildController';

import { DomainsController } from './controllers/DomainsController';
export { DomainsController } from './controllers/DomainsController';

import { SystemController } from './controllers/SystemController';
export { SystemController } from './controllers/SystemController';

import { TnpProjectController } from './controllers/TnpProjectController';
export { TnpProjectController } from './controllers/TnpProjectController';

export const Controllers: Morphi.Base.Controller<any>[] = [
BuildController,
DomainsController,
SystemController,
TnpProjectController
].concat(BaselineControllers as any) as any;

//#region @backend

import { Helpers } from "morphi";
import * as _ from 'lodash'

export function controllers<ADDITIONAL={}>(decoratorsControllers?: ADDITIONAL) {
return _.merge(controllersBaseline.controllers(), {

BuildController: Helpers.getSingleton<BuildController>(BuildController),

DomainsController: Helpers.getSingleton<DomainsController>(DomainsController),

SystemController: Helpers.getSingleton<SystemController>(SystemController),

TnpProjectController: Helpers.getSingleton<TnpProjectController>(TnpProjectController),
}  );
}
//#endregion
